### ISSUE TITLE
How to Clear Apollo Cache After Each Test?

### ISSUE THREAD

**Issue by joncursi** [benawad/apollo-mocked-provider#1]
I noticed that mock data is being stored in the cache and being re-used across tests. `afterEach(cleanup);` doesn't appear to be working here:

```jsx
/**
 * @prettier
 */

/* eslint-disable filenames/match-regex */
/* eslint-disable @typescript-eslint/explicit-function-return-type */

import * as React from 'react';
import { cleanup } from '@testing-library/react';
import constant from 'lodash/constant';

import { ApolloMockedProvider } from '~/test/utils/apollo';
import render from '~/test/utils/render';

import AuthAccount from '.';

afterEach(cleanup);

describe('components/AuthAccount', () => {
  test('renders children when user exists', async () => {
    const { getByText } = render(
      <ApolloMockedProvider
        customResolvers={{
          Query: () => ({
            me: () => ({
              _id: 'myId123',
            }),
          }),
        }}
      >
        <AuthAccount>
          <div>This should render</div>
        </AuthAccount>
      </ApolloMockedProvider>,
    );

    await Promise.resolve();

    getByText('This should render');
  });

  test('does not render children when user does not exist', async () => {
    const { debug, getByText } = render(
      <ApolloMockedProvider
        customResolvers={{
          Query: () => ({
            me: constant(null),
          }),
        }}
      >
        <AuthAccount>
          <div>This should not render</div>
        </AuthAccount>
      </ApolloMockedProvider>,
    );

    await Promise.resolve();

    getByText('This should not render'); // it still renders with id `myId123` :(

    debug();
  });
});
```

**Comment by joncursi** [comment]
I feel like this would be solved via `client.clearStore()`, but I don't have access to the `client` object that is created under the hood via `ApolloMockedProvider`.

**Comment by NickTomlin** [comment]
I've been bitten by this as well. I've added a PR to default to using a new `InMemoryCache` per component (but also allow overrides).

**Comment by sarfata** [comment]
Same problem here. I am using these providers with Storyboard and I am getting interference between my different stories.

I just call `new InMemoryCache()` in the `createApollo*Provider()` functions instead of reusing the same cache:

```jsx
export const ApolloMockedProvider = createApolloMockedProvider(typeDefs, new InMemoryCache());
export const ApolloErrorProvider = createApolloErrorProvider(new InMemoryCache());
export const ApolloLoadingProvider = createApolloLoadingProvider(new InMemoryCache());
```
Maybe @benawad could comment and tell us why the example is reusing the cache? In which cases is this helpful?

**Comment by benawad** [comment]
Sorry guys, I don't know why I was getting a notification before about this.

I don't have my computer with me until the 19th. I'll merge the prs and publish a new version then.

**Comment by alessio-libardi** [comment]
For anyone still facing some issues between tests you can also use reset the whole cache before each test:

```js
beforeEach(() => {
  return cache.reset()
})
```

Obviously it doesn't cover all the different use cases but it covered mine and hopefully some of yours! 😄

**Comment by hshoja** [comment]
> For anyone still facing some issues between tests you can also use reset the whole cache before each test:
> 
> ```js
> beforeEach(() => {
>   return cache.reset()
> })
> ```
> 
> Obviously it doesn't cover all the different use cases but it covered mine and hopefully some of yours! 😄

didn't work for me.

**Comment by kasparas-anusauskas** [comment]
`cache.reset` exists on the instance of `InMemoryCache`, but doesn't seem to actually reset it. Does anyone know if it is supposed to? Can't find it in the API docs of Apollo.

**Comment by kevinthefremen** [comment]
I am still seeing issues with this. I altered the sandbox example in the apollo docs to recreate the issue. By adding a beforeEach and then altering the tests slightly the new mock does not override the original. This produces a failing test. The odd thing is the error test at the bottom passes. It is almost like the cache is only re-written when the result is different enough...

```import "@testing-library/jest-dom";
import { render, screen } from "@testing-library/react";
import { MockedProvider } from "@apollo/client/testing";
import { GET_DOG_QUERY, Dog } from "./dog";

const mocks = [
  {
    request: {
      query: GET_DOG_QUERY,
      variables: {
        name: "Buck"
      }
    },
    result: {
      data: {
        dog: { id: "1", name: "Buck", breed: "bulldog" }
      }
    }
  }
];

beforeEach(() => {
  render(
    <MockedProvider mocks={mocks} addTypename={false}>
      <Dog name="Buck" />
    </MockedProvider>
  );
});

it("should render dog", async () => {
  const dogMock = {
    request: {
      query: GET_DOG_QUERY,
      variables: { name: "Buck" }
    },
    result: {
      data: {id: "1", name: "Buck", breed: "poodle" }
    }
  };
  render(
    <MockedProvider mocks={[dogMock]} addTypename={false}>
      <Dog name="Buck" />
    </MockedProvider>
  );
  expect(await screen.findByText("Loading...")).toBeInTheDocument();
  expect(await screen.findByText("Buck is a poodle")).toBeInTheDocument();
});

it("should show error UI", async () => {
  const dogMock = {
    request: {
      query: GET_DOG_QUERY,
      variables: { name: "Buck" }
    },
    error: new Error("An error occurred")
  };
  render(
    <MockedProvider mocks={[dogMock]} addTypename={false}>
      <Dog name="Buck" />
    </MockedProvider>
  );
  expect(await screen.findByText("An error occurred")).toBeInTheDocument();
});
```

**Comment by Polyhistor** [comment]
Issue still exist in 2023.

**Comment by kskonecka** [comment]
setting `fetch-policy` to `network-only`, or `no-cache` fixed it for me :
```
<MockedProvider
    mocks={mocks}
    cache={cache}
    defaultOptions={{
        watchQuery: {
            fetchPolicy: 'network-only',
         },
      }}
>
   {children}
</MockedProvider>
```

**Comment by kevinthefremen** [comment]
@kskonecka Your solution does seem to fix the issue. Perhaps rather than a fix this could be added to the docs? It seems like that is the intended functionality but I imagine it is relatively common to test a variety of mock data responses. 

One other recommendation I can make based on my own code base is to refactor your components to handle the return data in a separate child component. This means you to use the `MockProvider` for parent components who's logic contains only successful, loading, error; mock any child components. Following SOLID principles that is likely the best anyways, but I will step off my soapbox for now.
