### ISSUE TITLE
Add option for globalMocks

### ISSUE THREAD

**Issue by Poky85** [benawad/apollo-mocked-provider#10]
[Original post](https://www.freecodecamp.org/news/a-new-approach-to-mocking-graphql-data-1ef49de3d491/) suggests a globalMocks option for passing base resolver mocks used across multiple tests (non-working [gist here](https://gist.github.com/stubailo/c010ba4d947928da769e0f5acf1eb3d5#file-apollomockingprovider-jsx))

This presumes "merge resolvers" functionality to be done. Guess that we are [waiting for this PR](https://github.com/apollographql/graphql-tools/pull/1084) from graphql-tools repo, right?

**Comment by benawad** [comment]
I haven't looked into it, but probably

**Comment by lorensr** [comment]
Here's the merge function: https://www.graphql-tools.com/docs/api/modules/merge#mergeresolvers

Looks like could be used here:

https://github.com/benawad/apollo-mocked-provider/blob/master/src/createApolloMockedProvider.tsx#L28
