### ISSUE TITLE
Changing path where updated typeDefs is located

### ISSUE THREAD

**Issue by fabio-felizzi** [benawad/apollo-mocked-provider#14]
Hello,
I'm trying to figure out how to change the path where typeDefs.js is generated. Is there an option within the fetchTypeDefs object?

Rather than downloading it to the root of my project, could I set it to be generated somewhere else?

**Comment by benawad** [comment]
you can pass in the path https://github.com/benawad/apollo-mocked-provider/blob/master/src/fetchTypeDefs.ts#L16

**Comment by fabio-felizzi** [comment]
> you can pass in the path https://github.com/benawad/apollo-mocked-provider/blob/master/src/fetchTypeDefs.ts#L16

Awesome thank you!
