### ISSUE TITLE
Add support for Apollo local state with client resolvers

### ISSUE THREAD

**Issue by sliptype** [benawad/apollo-mocked-provider#21]
When managing local state with the `@client` directive as described in the [Apollo docs](https://www.apollographql.com/docs/tutorial/local-state/), the mocking fails because the client resolvers are not available to the`ApolloClient` created here: https://github.com/benawad/apollo-mocked-provider/blob/29a9d46536a0f4ea970f50bd46d8e4010efe2bff/src/createApolloMockedProvider.tsx#L41-L51

I think local state can be supported by adding a `clientResolvers` option to `ApolloMockedProviderOptions` and passing that (as `resolvers`) to the `ApolloClient` when it's created.

Let me know if this is already supported and I am just missing something.

If you think this would be good change, I can make a PR.

**Comment by benawad** [comment]
Yeah a PR for that would be great!
