### ISSUE TITLE
Does the resolver function returns same data for multiple calls from same Query?

### ISSUE THREAD

**Issue by nucab** [benawad/apollo-mocked-provider#25]
I have this problem my resolver doesn't return the data in the second call for the same Query.

**Comment by wongm3** [comment]
@noahjohn9259 Did you close this because you figured it out? If so can you share the solution?

**Comment by nucab** [comment]
@wongm3 . i can't recall my issue about it . my apologies. maybe if you can post your issue i might be able to recall it.

**Comment by wongm3** [comment]
I have a test that has two different components that hit the same resolver. And the second query that hits that resolver gets no data back.
