### ISSUE TITLE
Throwing an Error doesn't cause an Error to be thrown

### ISSUE THREAD

**Issue by lorensr** [benawad/apollo-mocked-provider#31]
I have the following in my app: `doMutation().catch(e => doSomething(e.graphQLErrors))`. 
- When I use my app and there's an error in the mutation, `doSomething()` is called. 
- When I return an error from my `ApolloMockedProvider` custom resolver, `doSomething()` is not called.

Repro: https://github.com/lorensr/apollo-mocked-provider/tree/repro-no-throw

The below `console.log` is not called when running `npm test -- -t "mock Mutation"`

https://github.com/lorensr/apollo-mocked-provider/commit/1682ac4826aae2d8ee0d29bfe92c260e9bf36a1b

> Note that if you add a `.then(response)`, the error is contained in `response.errors`.

**Comment by lorensr** [comment]
This issue is fixed by removing this line:

https://github.com/benawad/apollo-mocked-provider/blob/master/src/createApolloMockedProvider.tsx#L52

However, this line was added for a reason:

https://github.com/benawad/apollo-mocked-provider/issues/4#issuecomment-517791735

We could replace it with the `defaultOptions` parameter @NickTomlin suggested. This would be a breaking change, but seems better to me. Alternative would be to keep the `'all'` default *and* add `defaultOptions` so people like me can override it back to the [AC default](https://www.apollographql.com/docs/react/data/error-handling/#error-policies) of `none`.

**Comment by benawad** [comment]
I'm good if you want to add the breaking change

**Comment by sarfata** [comment]
@lorensr what does your server return when there is an error? What type of errors trigger the `catch()`?

I am having a hard time finding a definitive reference on this but in my experience a lot of errors do not trigger the catch and just return an ApolloError in the mutation result. I think that is what the current code simulates and for me it seemed to match behavior in "real life" (but this is a confusing area for sure).

[From the doc](https://www.apollographql.com/docs/react/data/mutations/#result):

> Mutation Result
> - error | ApolloError | Any errors returned from the mutation

**Comment by lorensr** [comment]
@sarfata I imagine many people either set the errorPolicy and/or use an error link to catch errors, in which case a mutation promise wouldn't reject. But if the errorPolicy is `none`, GraphQL errors (`errors` field in the response JSON) are treated like network errors, which in my experience are rejected. It looks like `useMutation` doesn't say when `mutate` promise rejects, but the AC function says it does:

> This resolves a single mutation according to the options specified and returns a Promise which is either resolved with the resulting data or rejected with an error.

https://www.apollographql.com/docs/react/api/core/ApolloClient/#ApolloClient.mutate

The code I use that results in a GraphQL error is `throw new Error('unauthorized')` from a resolver in Apollo Server.

```json
{"data":{"removeReview":null},"errors":[{"locations":[{"column":35,"line":1}],"message":"unauthorized","path":["removeReview"]}]}
```

**Comment by lorensr** [comment]
Working on the test for the PR and ran into this:

https://github.com/testing-library/react-testing-library/issues/828

and I got dejavu 😆

**Comment by sarfata** [comment]
Yeah sounds like this is a poorly documented behavior (or too flexible with `errorPolicy`). I still dont understand exactly how it is supposed to work but dont hold up for me! thanks for taking the time to research.
