### ISSUE TITLE
Custom resolver with no data

### ISSUE THREAD

**Issue by draxx318** [benawad/apollo-mocked-provider#36]
Is possible to pass a custom resolver with no data to the ApolloMockedProvider to simulate a scenario where the query returns an empty array?

**Comment by sarfata** [comment]
Yes. Just return an empty array.

For example, I have this in my project:

```typescript
stories.add("Boat selector with no boat", () => (
  <ApolloMockedProvider
    customResolvers={{
      Query: () => ({
        me: () => ({
          boats: [],
        }),
      }),
    }}
  >
    <ControlledBoatSelectorInput />
  </ApolloMockedProvider>
))
```

If this does not work for you, please send more details.

**Comment by draxx318** [comment]
Thanks, works like a charm. I was trying to do it the same way but probably had something wrong with the implementation.
