### ISSUE TITLE
Error handling within MockedProvider

### ISSUE THREAD

**Issue by NickTomlin** [benawad/apollo-mocked-provider#4]
The current `createApolloErrorProvider` approach has a separate "throw an error for all requests". This is useful for inspecting the behavior of errors on initial load, but breaks down for me when I have a view that may render some data with a query (like a list of items) and execute another query/mutation on that data.

I'd prefer to be able to control the error handling within my custom resolvers. I've taken a crack at it [here](https://github.com/NickTomlin/apollo-mocked-provider/commit/9d6317b37b363e7f5b433de37197f89defd33b96). Here is a snippet of usage:

```jsx
<MockedProvider
  customResolvers={{
    Query: () => ({
      todo: (_obj: any, args: any) => {
        console.log(args.id)
        throw new Error('Boom');
      },
      todos: () => [
        {
          text: 'Success',
        },
      ],
    }),
  }}
>
```

This would allow a `todos` query to execute, and then throw an error when `todo(id: ID)` is executed. Optionally, a resolver can inspect its arguments and conditionally throw an error. This would allow for a more natural way of handling complex error scenarios.

**Comment by benawad** [comment]
I like that approach, I'd be happy to merge a pr for that.

**Comment by sarfata** [comment]
@NickTomlin I could use this too. Any reason you have not made a PR yet?

~~If you do not have time, I could take your fork, check that it builds with recent changes and make the PR.~~ PR ready to merge :)

**Comment by NickTomlin** [comment]
@sarfata thanks for merging! My wife and I recently welcomed a child so I haven't had any time to focus on this 😄 

One issue that I did encounter (which was why I hadn't merged my initial work) is that errors thrown in mutation resolvers do not work as expected. By default, they caught by the error handler and also thrown by Apollo. Here's a [reproduction](https://github.com/NickTomlin/apollo-mocked-provider/commit/6ec2cbd70837511e2d3fd7dc92fa9683a67ddef1) (`npm t` should result in a failing test). More details in https://github.com/apollographql/react-apollo/issues/2614

The "fix" is to either specify an `onError` policy on the `Mutation` (which is ugly, because you shouldn't have to do this just for tests) or to set a mutation error policy of `all` on the client:

```
const client = new ApolloClient({
  defaultOptions: {
    mutate: {
      errorPolicy: 'all'
    }
  },
});
```

If you add the `defaultOptions` snippet to `createApolloMockedProvider` the test in my reproduction branch should work. It feels a little weird to default the error policy for all the mocked providers. If there's not a better fix we could allow passing a `defaultOptions` object to `createApolloMockedProvider` which could override that behavior.

**Comment by sarfata** [comment]
Hey @NickTomlin Congrats on the baby! Sorry for the delay here. Just wanted to acknowledge and say that I will get around to doing that and pushing a new PR. Thanks for pointing this out.

**Comment by netweng** [comment]
i have the problem when throw error in mutation, can this be fixed or i need to fork the repo and add the defaultOptions for errorPolicy.

**Comment by benawad** [comment]
@netweng happy to merge a pr

**Comment by lorensr** [comment]
Here's a problem I'm having with this feature: https://github.com/benawad/apollo-mocked-provider/issues/31
